version: 2
updates:
  - package-ecosystem: bundler
    directory: "/backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1
  - package-ecosystem: github-actions
    directory: "/backend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1
  - package-ecosystem: npm
    directory: "/frontend"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    cooldown:
      default-days: 1
